import 'trip_model.dart';

final Trip mockTripDetail = Trip(
  id: '1',
  title: 'Da Nang Summer Escape',
  destination: 'ÄÃ  Náºµng, Viá»‡t Nam',
  startDate: DateTime(2023, 10, 12),
  endDate: DateTime(2023, 10, 16),
  travelers: 2,
  totalStops: 18,
  distanceKm: 42.0,
  estimatedBudget: '4.2M',
  optimized: true,
  coverImage: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b',
  days: [
    TripDay(
      dayIndex: 1,
      date: DateTime(2023, 10, 12),
      title: 'KhÃ¡m phÃ¡ ÄÃ  Náºµng & Biá»ƒn Má»¹ KhÃª',
      subtitle: 'Thá»© Hai, 12 ThÃ¡ng 10 Â· 5 hoáº¡t Ä‘á»™ng',
      activities: [
        ItineraryActivity(
          id: 'a1',
          startTime: '08:00',
          endTime: '09:15',
          title: 'BÃ¡nh mÃ¬ PhÆ°á»£ng & CÃ  phÃª muá»‘i',
          category: 'Ä‚n sÃ¡ng',
          duration: '1h15m',
          description: 'Khá»Ÿi Ä‘á»™ng ngÃ y má»›i vá»›i hÆ°Æ¡ng vá»‹ Ä‘áº·c trÆ°ng',
          icon: 'restaurant',
          rating: 4.8,
          bookingStatus: 'ÄÃ£ xÃ¡c nháº­n Ä‘áº·t chá»—',
        ),
        ItineraryActivity(
          id: 'a2',
          startTime: '',
          endTime: '',
          title: 'ThÃªm cháº·ng trung chuyá»ƒn / Cafe nghá»‰',
          category: '',
          duration: '',
          description: '',
          isTransfer: true,
        ),
        ItineraryActivity(
          id: 'a3',
          startTime: '09:30',
          endTime: '11:30',
          title: 'Danh tháº¯ng NgÅ© HÃ nh SÆ¡n (Marble Mountains)',
          category: 'Tham quan',
          duration: '2h00m',
          description: '',
          imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246',
          overlayText: '850m Ä‘i bá»™',
          aiSuggestion: 'NÃªn leo Ä‘á»‰nh Thá»§y SÆ¡n buá»•i sÃ¡ng sá»›m trÆ°á»›c 10:30 Ä‘á»ƒ trÃ¡nh náº¯ng gáº¯t vÃ  chá»¥p áº£nh vÃ²m Ä‘á»™ng Huyá»n KhÃ´ng Ä‘áº¹p nháº¥t.',
        ),
        ItineraryActivity(
          id: 'a4',
          startTime: '12:00',
          endTime: '13:30',
          title: 'Bá»¯a trÆ°a MÃ¬ Quáº£ng áº¿ch Báº¿p Trang',
          category: 'Ä‚n trÆ°a',
          duration: '1h30m',
          description: 'ThÆ°á»Ÿng thá»©c Ä‘áº·c sáº£n MÃ¬ Quáº£ng thá»‘ truyá»n thá»‘ng, phÃ²ng mÃ¡y láº¡nh nghá»‰ ngÆ¡i tiá»‡n lá»£i.',
          icon: 'local_dining',
        ),
        ItineraryActivity(
          id: 'a5',
          startTime: '14:30',
          endTime: '17:30',
          title: 'BÃ£i biá»ƒn Má»¹ KhÃª & CÃ  phÃª TrÃ¬nh Biá»ƒn',
          category: 'Giáº£i trÃ­',
          duration: '3h00m',
          description: 'Táº¯m biá»ƒn thÆ° giÃ£n, ngáº¯m cÃ¡t má»‹n vÃ  thÆ°á»Ÿng thá»©c cÃ  phÃª bÆ¡ bÃ©o ngáº­y sÃ¡t bá» sÃ³ng.',
          imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
          overlayText: 'Äiá»ƒm ngáº¯m hoÃ ng hÃ´n rá»±c rá»¡',
        ),
        ItineraryActivity(
          id: 'a6',
          startTime: '18:30',
          endTime: '21:30',
          title: 'Háº£i sáº£n NÄƒm Äáº£nh & Check-in Cáº§u Rá»“ng',
          category: 'Ä‚n tá»‘i',
          duration: '3h00m',
          description: 'Tiá»‡c háº£i sáº£n tÆ°Æ¡i sá»‘ng giÃ¡ bÃ¬nh dÃ¢n, sau Ä‘Ã³ dáº¡o bá»™ bá» sÃ´ng HÃ n xem Cáº§u Rá»“ng biá»ƒu diá»…n phun lá»­a vÃ  nÆ°á»›c.',
          icon: 'nightlife',
          specialBadge: '21:00 Phun lá»­a',
        ),
      ],
    ),
    TripDay(dayIndex: 2, date: DateTime(2023, 10, 13), title: 'BÃ  NÃ  Hills', subtitle: 'Thá»© Ba, 13 ThÃ¡ng 10', activities: []),
    TripDay(dayIndex: 3, date: DateTime(2023, 10, 14), title: 'Há»™i An', subtitle: 'Thá»© TÆ°, 14 ThÃ¡ng 10', activities: []),
    TripDay(dayIndex: 4, date: DateTime(2023, 10, 15), title: 'CÃ¹ Lao ChÃ m', subtitle: 'Thá»© NÄƒm, 15 ThÃ¡ng 10', activities: []),
    TripDay(dayIndex: 5, date: DateTime(2023, 10, 16), title: 'Mua sáº¯m & Trá»Ÿ vá»', subtitle: 'Thá»© SÃ¡u, 16 ThÃ¡ng 10', activities: []),
  ],
);
