
import 'trip_model.dart';

final List<Trip> mockTripsList = [
  Trip(
    id: 'danang-2026',
    title: 'Khám phá Đà Nẵng',
    destination: 'Đà Nẵng & Hội An, Việt Nam',
    startDate: DateTime(2026, 10, 12),
    endDate: DateTime(2026, 10, 15),
    travelers: 2,
    totalStops: 18,
    distanceKm: 42.0,
    estimatedBudget: '4.2M',
    optimized: true,
    coverImage: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b',
    days: [], // Detail will use its own mock
    status: 'upcoming',
    category: 'Biển & Khám phá',
    progress: 0.8,
    aiPlanned: true,
    checklist: {
      'Vé máy bay': true,
      'Khách sạn': true,
      'Lịch trình': true,
      'Nhà hàng': false,
    },
  ),
  Trip(
    id: 'phuquoc-2026',
    title: 'Nghỉ dưỡng Phú Quốc',
    destination: 'Phú Quốc, Kiên Giang',
    startDate: DateTime(2026, 11, 20),
    endDate: DateTime(2026, 11, 24),
    travelers: 2,
    totalStops: 12,
    distanceKm: 30.0,
    estimatedBudget: '8.0M',
    optimized: false,
    coverImage: 'https://images.unsplash.com/photo-1588668214407-6ea9a6d8c272',
    days: [],
    status: 'planning',
    category: 'Resort & Biển ngọc',
    progress: 0.3,
    aiPlanned: false,
  ),
  Trip(
    id: 'dalat-2026',
    title: 'Vi vu Đà Lạt',
    destination: 'Đà Lạt, Lâm Đồng',
    startDate: DateTime(2026, 12, 10),
    endDate: DateTime(2026, 12, 13),
    travelers: 4,
    totalStops: 9,
    distanceKm: 25.0,
    estimatedBudget: '3.5M',
    optimized: false,
    coverImage: 'https://images.unsplash.com/photo-1626587979672-0050e828d506',
    days: [],
    status: 'draft',
    category: 'Săn mây & Cafe',
    progress: 0.1,
    aiPlanned: false,
  ),
  Trip(
    id: 'hoian-2027',
    title: 'Khám phá Hội An',
    destination: 'Hội An, Quảng Nam',
    startDate: DateTime(2027, 1, 15),
    endDate: DateTime(2027, 1, 17),
    travelers: 2,
    totalStops: 6,
    distanceKm: 15.0,
    estimatedBudget: '2.5M',
    optimized: true,
    coverImage: 'https://images.unsplash.com/photo-1582236968604-ee5ea861a4c9',
    days: [],
    status: 'completed',
    category: 'Phố cổ & Đèn lồng',
    progress: 1.0,
    aiPlanned: true,
  ),
];

