
import 'trip_model.dart';

final Trip mockTripDetail = Trip(
  id: '1',
  title: 'Da Nang Summer Escape',
  destination: 'Đà Nẵng, Việt Nam',
  startDate: DateTime(2023, 10, 12),
  endDate: DateTime(2023, 10, 16),
  travelers: 2,
  totalStops: 18,
  distanceKm: 42.0,
  estimatedBudget: '4.2M',
  optimized: true,
  coverImage: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b',
  days: [
    TripDay(
      dayIndex: 1,
      date: DateTime(2023, 10, 12),
      title: 'Khám phá Đà Nẵng & Biển Mỹ Khê',
      subtitle: 'Thứ Hai, 12 Tháng 10 · 5 hoạt động',
      activities: [
        ItineraryActivity(
          id: 'a1',
          startTime: '08:00',
          endTime: '09:15',
          title: 'Bánh mì Phượng & Cà phê muối',
          category: 'Ăn sáng',
          duration: '1h15m',
          description: 'Khởi động ngày mới với hương vị đặc trưng',
          icon: 'restaurant',
          rating: 4.8,
          bookingStatus: 'Đã xác nhận đặt chỗ',
        ),
        ItineraryActivity(
          id: 'a2',
          startTime: '',
          endTime: '',
          title: 'Thêm chặng trung chuyển / Cafe nghỉ',
          category: '',
          duration: '',
          description: '',
          isTransfer: true,
        ),
        ItineraryActivity(
          id: 'a3',
          startTime: '09:30',
          endTime: '11:30',
          title: 'Danh thắng Ngũ Hành Sơn (Marble Mountains)',
          category: 'Tham quan',
          duration: '2h00m',
          description: '',
          imageUrl: 'https://images.unsplash.com/photo-1585032226651-759b368d7246',
          overlayText: '850m đi bộ',
          aiSuggestion: 'Nên leo đỉnh Thủy Sơn buổi sáng sớm trước 10:30 để tránh nắng gắt và chụp ảnh vòm động Huyền Không đẹp nhất.',
        ),
        ItineraryActivity(
          id: 'a4',
          startTime: '12:00',
          endTime: '13:30',
          title: 'Bữa trưa Mì Quảng ếch Bếp Trang',
          category: 'Ăn trưa',
          duration: '1h30m',
          description: 'Thưởng thức đặc sản Mì Quảng thố truyền thống, phòng máy lạnh nghỉ ngơi tiện lợi.',
          icon: 'local_dining',
        ),
        ItineraryActivity(
          id: 'a5',
          startTime: '14:30',
          endTime: '17:30',
          title: 'Bãi biển Mỹ Khê & Cà phê Trình Biển',
          category: 'Giải trí',
          duration: '3h00m',
          description: 'Tắm biển thư giãn, ngắm cát mịn và thưởng thức cà phê bơ béo ngậy sát bờ sóng.',
          imageUrl: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24',
          overlayText: 'Điểm ngắm hoàng hôn rực rỡ',
        ),
        ItineraryActivity(
          id: 'a6',
          startTime: '18:30',
          endTime: '21:30',
          title: 'Hải sản Năm Đảnh & Check-in Cầu Rồng',
          category: 'Ăn tối',
          duration: '3h00m',
          description: 'Tiệc hải sản tươi sống giá bình dân, sau đó dạo bộ bờ sông Hàn xem Cầu Rồng biểu diễn phun lửa và nước.',
          icon: 'nightlife',
          specialBadge: '21:00 Phun lửa',
        ),
      ],
    ),
    TripDay(
      dayIndex: 2,
      date: DateTime(2023, 10, 13),
      title: 'Bà Nà Hills',
      subtitle: 'Thứ Ba, 13 Tháng 10',
      activities: [],
    ),
    TripDay(
      dayIndex: 3,
      date: DateTime(2023, 10, 14),
      title: 'Hội An',
      subtitle: 'Thứ Tư, 14 Tháng 10',
      activities: [],
    ),
    TripDay(
      dayIndex: 4,
      date: DateTime(2023, 10, 15),
      title: 'Cù Lao Chàm',
      subtitle: 'Thứ Năm, 15 Tháng 10',
      activities: [],
    ),
    TripDay(
      dayIndex: 5,
      date: DateTime(2023, 10, 16),
      title: 'Mua sắm & Trở về',
      subtitle: 'Thứ Sáu, 16 Tháng 10',
      activities: [],
    ),
  ],
);

