"""initial_schema_phase1

Revision ID: 7dbb08243517
Revises: 
Create Date: 2026-10-02 22:49:59.590241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '7dbb08243517'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_chunks')
    op.drop_table('user_preferences')
    op.drop_index(op.f('idx_trip_user'), table_name='trips')
    op.drop_table('trips')
    op.drop_table('trip_items')
    op.drop_table('sysdiagrams')
    op.drop_index(op.f('idx_messages_conversation'), table_name='messages')
    op.drop_table('messages')
    op.drop_table('ai_context')
    op.drop_table('conversations')
    op.alter_column('categories', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('hotel_details', 'place_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('FK__hotel_det__place__5CD6CB2B'), 'hotel_details', type_='foreignkey')
    op.create_foreign_key(None, 'hotel_details', 'places', ['place_id'], ['id'])
    op.alter_column('knowledge', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('knowledge', 'place_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('knowledge', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.drop_index(op.f('idx_knowledge_place'), table_name='knowledge')
    op.drop_constraint(op.f('FK__knowledge__place__6754599E'), 'knowledge', type_='foreignkey')
    op.create_foreign_key(None, 'knowledge', 'places', ['place_id'], ['id'])
    op.alter_column('opening_hours', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('opening_hours', 'place_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('FK__opening_h__place__6383C8BA'), 'opening_hours', type_='foreignkey')
    op.create_foreign_key(None, 'opening_hours', 'places', ['place_id'], ['id'])
    op.alter_column('place_images', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('place_images', 'place_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('place_images', 'is_primary',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.drop_constraint(op.f('FK__place_ima__place__60A75C0F'), 'place_images', type_='foreignkey')
    op.create_foreign_key(None, 'place_images', 'places', ['place_id'], ['id'])
    op.alter_column('places', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('places', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('places', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('places', 'category_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('places', 'is_deleted',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
    op.drop_index(op.f('idx_places_category'), table_name='places')
    op.drop_index(op.f('idx_places_location'), table_name='places')
    op.alter_column('restaurant_details', 'place_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint(op.f('FK__restauran__place__59FA5E80'), 'restaurant_details', type_='foreignkey')
    op.create_foreign_key(None, 'restaurant_details', 'places', ['place_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'updated_at',
               existing_type=sa.DATETIME(),
               type_=sqlmodel.sql.sqltypes.UTCDateTime(),
               nullable=False,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('users', 'role',
               existing_type=sa.NVARCHAR(length=20, collation='Vietnamese_CI_AS'),
               nullable=False,
               existing_server_default=sa.text("('USER')"))
    op.alter_column('users', 'is_active',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((1))'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((1))'))
    op.alter_column('users', 'role',
               existing_type=sa.NVARCHAR(length=20, collation='Vietnamese_CI_AS'),
               nullable=True,
               existing_server_default=sa.text("('USER')"))
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('users', 'updated_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('users', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'restaurant_details', type_='foreignkey')
    op.create_foreign_key(op.f('FK__restauran__place__59FA5E80'), 'restaurant_details', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.alter_column('restaurant_details', 'place_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_index(op.f('idx_places_location'), 'places', ['location'], unique=False)
    op.create_index(op.f('idx_places_category'), 'places', ['category_id'], unique=False)
    op.alter_column('places', 'is_deleted',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('places', 'category_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('places', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.alter_column('places', 'updated_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('places', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'place_images', type_='foreignkey')
    op.create_foreign_key(op.f('FK__place_ima__place__60A75C0F'), 'place_images', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.alter_column('place_images', 'is_primary',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
    op.alter_column('place_images', 'place_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('place_images', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'opening_hours', type_='foreignkey')
    op.create_foreign_key(op.f('FK__opening_h__place__6383C8BA'), 'opening_hours', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.alter_column('opening_hours', 'place_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('opening_hours', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'knowledge', type_='foreignkey')
    op.create_foreign_key(op.f('FK__knowledge__place__6754599E'), 'knowledge', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_knowledge_place'), 'knowledge', ['place_id'], unique=False)
    op.alter_column('knowledge', 'created_at',
               existing_type=sqlmodel.sql.sqltypes.UTCDateTime(),
               type_=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(getdate())'))
    op.alter_column('knowledge', 'place_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('knowledge', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'hotel_details', type_='foreignkey')
    op.create_foreign_key(op.f('FK__hotel_det__place__5CD6CB2B'), 'hotel_details', 'places', ['place_id'], ['id'], ondelete='CASCADE')
    op.alter_column('hotel_details', 'place_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('categories', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               existing_server_default=sa.Identity(always=False, start=1, increment=1))
    op.create_table('conversations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('title', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__conversat__user___74AE54BC'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__conversa__3213E83F5C01DD69'))
    )
    op.create_table('ai_context',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('summary', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('FK__ai_contex__conve__7C4F7684'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__ai_conte__3213E83F5E7EBF8F'))
    )
    op.create_table('messages',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('sender', sa.NVARCHAR(length=10, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('content', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('audio_url', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('FK__messages__conver__787EE5A0'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__messages__3213E83FB163DD0C'))
    )
    op.create_index(op.f('idx_messages_conversation'), 'messages', ['conversation_id'], unique=False)
    op.create_table('sysdiagrams',
    sa.Column('name', sa.NVARCHAR(length=128, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('principal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diagram_id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('definition', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('diagram_id', name=op.f('PK__sysdiagr__C2B05B6154DA594C'))
    )
    op.create_table('trip_items',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('place_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planned_time', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.Column('note', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], name=op.f('FK__trip_item__place__03F0984C')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('FK__trip_item__trip___02FC7413'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__trip_ite__3213E83FB33BECA0'))
    )
    op.create_table('trips',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.NVARCHAR(length=255, collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__trips__user_id__00200768'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__trips__3213E83F8ACAE900'))
    )
    op.create_index(op.f('idx_trip_user'), 'trips', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('FK__user_pref__categ__6FE99F9F')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('FK__user_pref__user___6EF57B66'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__user_pre__3213E83FE466D3BE'))
    )
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('knowledge_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('content', sa.NVARCHAR(collation='Vietnamese_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('embedding', mssql.VARBINARY(), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(getdate())'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], name=op.f('FK__knowledge__knowl__6B24EA82'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__knowledg__3213E83F00878E5A'))
    )
    # ### end Alembic commands ###
